### ISSUE TITLE
Link sets not being recognized to build regulatory network

### ISSUE THREAD

**Issue by EMC2019** [CyTargetLinker/cytargetlinker#23]
Thank you for any assistance with the following issue: 
For my first attempt of Tutorial 1 and then using the same steps with my own files there was not an issue, however, now I cannot move past step 3 of the tutorial 1---a few days after I have successfully completed Tutorial 1 as well as having worked with one of my networks. 
The link sets don't appear to be recognized/they are not able to be selected and this problem occurs both with Tutorial 1 data sets and as well as my own:
<img width="1440" alt="Screen Shot 2019-11-07 at 5 55 25 AM" src="https://user-images.githubusercontent.com/57489866/68391201-45387600-0124-11ea-9dc6-48d7ff74aa44.png">

**Comment by mkutmon** [comment]
In this step, you first need to select a folder and not individual files. On MacOS this is a little tricky, because it allows you to go into folder and then you cannot select it anymore. If you go one level up and then only select the folder, you should be able to click "Choose". Then you can select the individual linksets when you click "Ok".

**Comment by EMC2019** [comment]
Thank you so much!
